.TH LCS 1 "Version 0.5.1: January 06 2024" "Collection of ldap utilities" "ldap collection"
.SH NAME
lcs \- LDAP create ssl-config.
.SH SYNOPSIS
.B lcs
.B "-h hostname"
[
.B "-a CA-cert"
] [
.B "-i | -r"
]
.SH DESCRIPTION
\fBlcs\fP will create an ldif configuration for an SSL and TLS enable
directory.
This will modify the base cn=config to allow encypted communications with the
directory.
You should place the certificate for the server in \fI/etc/ldap/ssl.crt\fP and
name it \fI<hostname>.crt\fP where <hostname> is the hostname of the ldap
server.
You must also place the key in \fI/etc/ldap/ssl.key/<hostname>.pem\fP.
The root CA certificate, if required, should be made available at 
\fI/etc/ssl/certs/<ca-name>.crt\fP where ca-name is the name of the ca-cert
file.
.SH OPTIONS
.IP "-h hostname"
Specify the hostname of the ldap server.
.IP "-a CA-cert"
Specify the name of the CA-cert file (minus the .crt postfix)
.IP -i
Create an insert ldif (this is the default)
.IP -r
Create a remove ldif (this will remove the configuration)
.SH ENVIRONMENT
There are no environment variables used in this program.
.SH AUTHOR
Iain M Conochie <iain-at-thargoid-dot-co-dot-uk>
.SH "SEE ALSO"
.BR lcdb(1)
.BR lcc(1)
.BR lcg(1)
.BR lcr(1)
.BR lcu(1)
.BR lck(1)
.BR lcou(1)
.BR lcdhcp(1)
