#
#
# Makefile.am for ldap-utils c programs
#
#
RM = rm -f
ECHO = echo
DIR = src
OLDDIR = old
SUBDIRS = src
bin_PROGRAMS = lcs lcc lcg lck lcu lcr lcdb

all:	$(bin_PROGRAMS)

.PHONY:	clean $(bin_PROGRAMS) old-all

$(bin_PROGRAMS):
	$(MAKE) -C $(DIR) $@

old-all:
	cd $(OLDDIR); make all

clean:
	cd $(DIR); make $@; cd ../$(OLDDIR); make $@

