#
#
# Makefile.am for ldap-utils c programs
#
#
RM = rm -f
ECHO = echo
DIR = src
OLDDIR = old
SUBDIRS = src
bin_PROGRAMS = lcs lcc lcg lck lcu lcr lcdb
old_PROGRAMS = lcd tsha gsha gsha2 sha1 lct ssha

all:	$(bin_PROGRAMS)

.PHONY:	clean $(bin_PROGRAMS) $(old_PROGRAMS)

$(bin_PROGRAMS):
	$(MAKE) -C $(DIR) $@

$(old_PROGRAMS):
	$(MAKE) -C $(OLDDIR) $@

clean:
	cd $(DIR); make $@; cd ../$(OLDDIR); make $@

