#
#
# Makefile for various small c programs
#
#
CC = gcc
RM = rm -f
ECHO = echo
CFLAGS = -D_XOPEN_SOURCE=700 -g -DLDAP_DEPRECATED
CPPFLAGS += -I../include/ `pkg-config --cflags glib-2.0` `pkg-config --cflags check`
LDFLAGS = -L../lib `pkg-config --libs-only-L glib-2.0` `pkg-config --libs check`
LDLIBS = -lailsaldap -lcrypto `pkg-config --libs-only-l glib-2.0` -lldap `pkg-config --libs check`
bin_PROGRAMS = check_get_ldif_domain


all:	$(bin_PROGRAMS)

bin:	$(bin_PROGRAMS)

clean:
	$(RM) *.o $(bin_PROGRAMS)
