#
#
# Makefile for various ldap c programs
#
#
CC = gcc
RM = rm -f
ECHO = echo
CFLAGS = -W -Wall -Wshadow -Wcast-qual -Wwrite-strings -Wunused -D_XOPEN_SOURCE=700 -g

# Add this as CPPFLAGS if you want to have bind authentication
PCFLAGS = -DLDAP_DEPRECATED

GCFLAGS = `pkg-config --cflags glib-2.0`
GLDFLAGS = `pkg-config --libs-only-L glib-2.0`
GLIBS = `pkg-config --libs-only-l glib-2.0`
LLDFLAGS = -L/lib/x86_64-linux-gnu -lldap
SLDFLAGS = -L/lib/x86_64-linux-gnu -lcrypto
bin_PROGRAMS =
shared_SOURCES =

all:	$(bin_PROGRAMS)

clean:
	$(RM) *.o $(bin_PROGRAMS)
