#
#
# Makefile for various ldap c libraries
#
#
CC = gcc
RM = rm -f
ECHO = echo
# Add this as CFLAGS if you want to have bind authentication
PCFLAGS = -DLDAP_DEPRECATED

CFLAGS = -W -Wall -Wshadow -Wcast-qual -Wwrite-strings -Wunused -D_XOPEN_SOURCE=700 $(PCFLAGS) -g
CPPFLAGS += -I../include/
lib_LIBRARIES = libailsaldap.a



CPPFLAGS += `pkg-config --cflags glib-2.0`
LDFLAGS += -L/lib/x86_64-linux-gnu
LDLIBS += -lldap -lcrypto -lgcrypt -lailsa
ARFLAGS = rvU
#LLDFLAGS = -L/lib/x86_64-linux-gnu -lldap
#SLDFLAGS = -L/lib/x86_64-linux-gnu -lcrypto
shared_SOURCES =

libs:	libailsaldap.a

libailsaldap.a:	libailsaldap.a(common.o) libailsaldap.a(password.o) libailsaldap.a(ldif.o) \
		libailsaldap.a(config.o) libailsaldap.a(gcrypt_hash.o)

libailsaldap.a(common.o):	common.o
	$(AR) $(ARFLAGS) $@ $<

libailsaldap.a(password.o):	password.o
	$(AR) $(ARFLAGS) $@ $<

libailsaldap.a(ldif.o):	ldif.o
	$(AR) $(ARFLAGS) $@ $<

libailsaldap.a(config.o):	config.o
	$(AR) $(ARFLAGS) $@ $<

libailsaldap.a(gcrypt_hash.o):	gcrypt_hash.o
	$(AR) $(ARFLAGS) $@ $<
.PHONY:	clean

clean:
	$(RM) *.o *.a
