#
#
# Makefile for various ldap c libraries
#
#
CC = gcc
RM = rm -f
ECHO = echo
CFLAGS = -W -Wall -Wshadow -Wcast-qual -Wwrite-strings -Wunused -D_XOPEN_SOURCE=700 -g
CPPFLAGS += -I../include/
lib_LIBRARIES = libailsaldap.a

# Add this as CPPFLAGS if you want to have bind authentication
PCFLAGS = -DLDAP_DEPRECATED

CPPFLAGS += `pkg-config --cflags glib-2.0`
LDFLAGS += -L/lib/x86_64-linux-gnu `pkg-config --libs-only-L glib-2.0`
LDLIBS += `pkg-config --libs-only-l glib-2.0` -lldap -lcrypto
ARFLAGS = rvU
#LLDFLAGS = -L/lib/x86_64-linux-gnu -lldap
#SLDFLAGS = -L/lib/x86_64-linux-gnu -lcrypto
shared_SOURCES =

libs:	libailsaldap.a

libailsaldap.a:	libailsaldap.a(common.o) libailsaldap.a(password.o) libailsaldap.a(ldif.o) libailsaldap.a(ailsa_kv_s.o)

libailsaldap.a(common.o):	common.o
	$(AR) $(ARFLAGS) $@ $<

libailsaldap.a(password.o):	password.o
	$(AR) $(ARFLAGS) $@ $<

libailsaldap.a(ldif.o):	ldif.o
	$(AR) $(ARFLAGS) $@ $<

libailsaldap.a(ailsa_kv_s.o):	ailsa_kv_s.o
	$(AR) $(ARFLAGS) $@ $<

.PHONY:	clean

clean:
	$(RM) *.o *.a
