#
#
# Makefile for various small c programs
#
#
CC = gcc
RM = rm -f
ECHO = echo
CFLAGS = -W -Wall -Wshadow -Wcast-qual -Wwrite-strings -Wunused -D_XOPEN_SOURCE=700 -g -DLDAP_DEPRECATED
CPPFLAGS += -I../include/
LDFLAGS = -L../lib
LDLIBS = -lailsaldap -lailsa -lcrypto -lldap -lgcrypt
bin_PROGRAMS = lcs lcg lcu lcr lcdb lck lcou lcsudo lcdhcp hh lds


all:	$(bin_PROGRAMS)

bin:	$(bin_PROGRAMS)

clean:
	$(RM) *.o $(bin_PROGRAMS) *.ldif ../*.ldif
