#
#
# Makefile for various small c programs
#
#
CC = gcc
RM = rm -f
ECHO = echo
CFLAGS = -W -Wall -Wshadow -Wcast-qual -Wwrite-strings -Wunused -D_XOPEN_SOURCE=700 -g -DLDAP_DEPRECATED
CPPFLAGS += -I../include/ `pkg-config --cflags glib-2.0`
LDFLAGS = -L../lib `pkg-config --libs-only-L glib-2.0`
LDLIBS = -lailsaldap -lailsa -lcrypto `pkg-config --libs-only-l glib-2.0` -lldap
bin_PROGRAMS = lcs lcg lcu lcr lcdb lck lcou lcsudo lcdhcp hh lds


all:	$(bin_PROGRAMS)

bin:	$(bin_PROGRAMS)

clean:
	$(RM) *.o $(bin_PROGRAMS) *.ldif ../*.ldif
